config/routes.rb
Rails.application.routes.draw do
  get 'shop/index'
  get 'shop/purchase'
  get 'shop/success'
  get 'shop/balance_not_enough'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'
end

app/models/product.rb
class Product
  attr_accessor :amount, :currency, :description
  def initialize
    set_xfers_config
  end

  def charge(user_api_token:)
    Xfers::Charge.create(
        :amount => amount,
        :currency => currency, # Refence https://currencysystem.com/codes/
        :order_id => SecureRandom.hex(5),
        :description => description,
        :return_url => 'http://localhost:3000/shop/success',
        :user_api_token => user_api_token
      )
  end

  private
    def set_xfers_config
      Xfers.set_api_key '3dehFLadwsxNUWe_sSp5ymBaQJB8yLzPyM1sRgkTDPk'
      Xfers.set_id_sandbox # Set the sandbox to id region
    end
end

app/models/user.rb
class User
  def initialize
    set_xfers_config
    begin
      @user = Xfers::User.retrieve
    rescue Xfers::XfersError => e
      puts e.to_s
    end
  end

  def id
    @user[:id]
  end

  def balance
    @user[:available_balance]
  end

  private
    def set_xfers_config
      # ASSUMPTION: because I don't create the login page
      # I set the api key in here.
      # in the future, will try to integrate the api key with gem "devise"
      # so when user login, I will set the api key in current_user
      Xfers.set_api_key 'gvPLaHoa7gX5F63aSM6v_ZQq9s2X4X74ztTvyfrgY2E'
      Xfers.set_id_sandbox # Set the sandbox to id region
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user

  private
    def set_user
      @user = User.new
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  before_action :set_sample_product

  def index
  end

  def purchase
    if params[:id] == 'food'
      if check_balance(product: @food)
        redirect_to shop_balance_not_enough_path 
      else
        redirect_to @food.charge(user_api_token: 'gvPLaHoa7gX5F63aSM6v_ZQq9s2X4X74ztTvyfrgY2E')[:return_url]
      end
    else
    end
  end

  def balance_not_enough
  end

  def success

  end

  def check_balance(product:)
    @user.balance.to_f <= product.amount.to_f
  end

  def set_sample_product
    @food = Product.new
    @food.amount = 1000000
    @food.currency = 'IDR'
    @food.description = 'Food'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/dashboard/index.html.erb
<p>
  <%= link_to 'Shop', shop_index_path %>
</p>

<p>
  Balance: Rp. <%= @user.balance %>  
</p>

<p>
  Welcome!
  You have successfully created your wallet.
  You can top up your wallet by transferring to the following bank:
</p>

<p>
  <b>Bank Name</b> BCA
  <b>Account Number</b> 1030612105678075
  <b>Unique ID</b> <%= @user.id%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shop/balance_not_enough.html.erb
balance_not_enough.html.erb

app/views/shop/index.html.erb
<%= link_to 'food', shop_purchase_path+'?id=food' %>

app/views/shop/purchase.html.erb
<h1>Shop#purchase</h1>
<p>Find me in app/views/shop/purchase.html.erb</p>

app/views/shop/success.html.erb
Purchased!